### PR TITLE
fix: remove redundant space

### LINKED ISSUE #296: Height of SVG is wrong
As you can see in the picture the SVG is higher than the actual block. This makes the inline use blocks look bad.

### PR DESCRIPTION
**Pull request by exKAZUu**
Close #296

Chrome browser on my Windows PC renders the following blocks with the following sizes.

- `when flag clicked`: 139 x 72.5
- `move (1) steps`: 149 x 56
- `(1) = (1)`: 145 x 40

This PR renders the corresponding SVGs with the following sizes:

- `when flag clicked`: 143 x 74
- `move (1) steps`: 153 x 58
- `(1) = (1)`: 149 x 42

### CODE REVIEW

File: scratch3/blocks.js [hunk 1]
```diff
@@ -703,7 +703,7 @@ ScriptView.prototype.draw = function(inside) {
   }
   this.height = y + 1
   if (!inside && !this.isFinal) {
-    this.height += block.hasPuzzle ? 44 : 36
+    this.height += block.hasPuzzle ? 8 : 0
```
Comment (Skagevang) [inline scratch3/blocks.js]: Why not 9 and 1? Isn't this cutting the bottom part by one?

Comment (exKAZUu) [reply scratch3/blocks.js]: 8 and 0 seem not to cut the bottom part (with my own eye), but, I feel we don’t need to reduce spaces aggressively.
Out of curiosity, how did you select 9 and 1?

Comment (Skagevang) [reply scratch3/blocks.js]: My mistake. This is correct. Should be ready to merge

**Comment by Skagevang** [comment]
@tjvr status for this one? :)

**Comment by exKAZUu** [comment]
@tjvr Sorry for the late response. I've fixed this PR as you advised me.
I've also confirmed the correct space is shown between scripts now.

File: scratch3/blocks.js [hunk 2]
```diff
@@ -750,6 +750,7 @@ DocumentView.prototype.render = function(cb) {
     script.y = height
     elements.push(SVG.move(0, height, script.draw()))
     height += script.height
+    if (i !== this.scripts.length - 1) height += 36
```
Comment (exKAZUu) [inline scratch3/blocks.js]: This space should be added only between two scripts

File: scratch3/blocks.js [hunk 3]
```diff
@@ -705,10 +705,10 @@ ScriptView.prototype.draw = function(inside) {
   }
   this.height = y + 1
   if (!inside && !this.isFinal) {
-    this.height += block.hasPuzzle ? 44 : 36
+    this.height += block.hasPuzzle ? 8 : 0
   }
   if (!inside && block.isGlow) {
-    this.height += 2 // TODO unbreak this
+    this.height += 7 // TODO unbreak this
```
Comment (exKAZUu) [inline scratch3/blocks.js]: This change is required when using `+` diff.

NOTE: this wasn't problematic because each script has redundant space due to `this.height += block.hasPuzzle ? 44 : 36`.

**Comment by exKAZUu** [comment]
@tjvr any chanche to review this again and merge it if okay? I'm confident that this change is useful because I've arleady used my patch in my several projects.

**Comment by dmalan** [comment]
Hi @tjvr, just wanted to chime in to say that we're experiencing the same symptom as well, which is particularly noticeable when including blocks within paragraphs of text or unordered lists. E.g., we're currently using the library for a set of course notes:

116479929-4f2cc800-a835-11eb-9d2d-8b5fd35a3fd4

Any chance @exKAZUu's PR is on the roadmap? Many thanks!

**Comment by RedGuy12** [comment]
I used this to fix it. Run it after `scratchblocks.renderMatching`.
```js
[...document.querySelectorAll(".scratchblocks svg")].forEach((svg) => {
  var bbox = svg.getBBox();
  svg.setAttribute("width", bbox.width + "px");
  svg.setAttribute("height", bbox.height + "px");
  svg.parentNode.setAttribute("style", `height: ${svg.getBoundingClientRect().height}px;`);
  // This fixes extra padding below scipts.
  // https://stackoverflow.com/a/14363879/11866686
  // https://github.com/scratchblocks/scratchblocks/pull/301
}
```

**Comment by tjvr** [comment]
Sorry, I haven’t had a chance to look at this yet!

**Comment by JackMorganNZ** [comment]
@tjvr Would it be possible to get an ETA on this? I see this PR has been here for nearly two years, so understand if you're unable to maintain this package anymore, we'll happy make a fork if required. Thanks for the great package, been using it for many years on the CS Unplugged website.

Screenshot from 2021-05-24 15-36-26

**Comment by dmalan** [comment]
> I used this to fix it.

@RedGuy12, do you find that that workaround actually clips the bottom of some SVGs by a couple pixels? E.g., for https://scratchblocks.github.io/#?style=scratch3&script=turn%20cw%20(15)%20degrees:

**height by default**

Screen Shot 2021-05-24 at 9 49 56 AM

**height after running [code](https://github.com/scratchblocks/scratchblocks/pull/301#issuecomment-829428605)**

Screen Shot 2021-05-24 at 9 53 12 AM

Screen Shot 2021-05-24 at 9 52 51 AM

Notice how the bottom of the block (including part of its border) is clipped slightly. 

We currently work around the clipping by adding 2px, albeit a bit hackishly:

```js
$('.scratchblocks svg').each(function(index, element) {
    const bbox = element.getBBox();
    const height = Math.floor(bbox.height) + 2; // Prevents clipping of bottom of some blocks
    $(element).attr('width', bbox.width);
    $(element).attr('height', height);
    $(element).parent().css('height', Math.ceil(element.getBoundingClientRect().height) + 'px');
});
```

**Comment by RedGuy12** [comment]
No I do not sorry
________________________________

**Comment by exKAZUu** [comment]
@tjvr (Just to confirm) is there no opportunity to merge this PR?

**Comment by tjvr** [comment]
Oops, closed this by mistake!

**Review by tjvr — APPROVED** [review]

**Comment by tjvr** [comment]
This looks good to me! Sorry it took so long to get around to this :sweat_smile:

**Comment by dmalan** [comment]
Hi @tjvr, @exKAZUu, just wanted to mention that we still seem to be seeing this symptom with v3.6.0 (and v3.5.2), whereby the `svg` element is ending up with a `height` attribute that's much larger than the SVG's actual height. E.g., 120.5 versus 178:

Screen Shot 2022-04-09 at 1 30 41 PM

This still seems to happen with the v3.6.0 generator, too. E.g., if you export https://scratchblocks.github.io/#?style=scratch3&script=when%20green%20flag%20clicked%0Aask%20%5BWhat's%20your%20name%3F%5D%20and%20wait%0Asay%20(join%20%5Bhello%2C%5D%20(answer)) as a PNG, it saves as the below, with its transparent background quite a bit taller too?

Screen Shot 2022-04-09 at 1 33 07 PM

**Comment by tjvr** [comment]
Oh no! How frustrating.

If you could open a new issue, I’ll try and take a look 🙏
